### PR TITLE
WIP TV Slideshow

### LINKED ISSUE #69: Create carousel for venue TVs
> so it would be like schedule -> sponsor slide -> schedule -> speaker/talk -> schedule -> sponsor (and so on)

### PR DESCRIPTION
**Pull request by DevinClark**
Don't merge yet.

You can view progress at /tv-day-1.html.

- [x] Build slideshow
- [ ] Finalize content
- [ ] Clean up content styles

If there's time:
- [ ] Add a slide for the speaker that is up next based on time.

Closes #69.

### CODE REVIEW

**Comment by the-simian** [comment]
overall i see what you're doing here. looks good so far
might see the main page - how it works and follow a similar pattern but wrap every partial in a 'slide'

**Comment by DevinClark** [comment]
Yeah that makes sense. I was really in the MVP stage last night.

**Comment by the-simian** [comment]
sorta like:

```
section#sponsorship.slide
 include sponsorship.jade

section#schedule-day-1.slide
 include schedule.jade

section#coc.slide
  include code-of-conduct.jade
```

**Comment by the-simian** [comment]
yeah you're on the right track

**Pull request merged**
